### ISSUE TITLE
Error while hashing in Irene

### ISSUE THREAD

**Issue by ldeviveiros** [project8/hornet#30]
While running a mantis acquisition, we get the following error messages from Hornet:

NOTICE > Sending <rid000000287_000000000.egg> to the classifier
ERROR > Error while hashing: exit status 1
NOTICE > Sending <rid000000287_000000001.egg> to the classifier
ERROR > Error while hashing: exit status 1

Otherwise, the run is acquired without problem, and it runs to the end.  We get one entry in the database for the first file:
http://portal.project8.org/RunTablesv1/runs_run_table_view.php?editid1=287
But the file_hash field is empty - it indicates the problem might be in calculating the hash, and not with communicating with the database.

**Comment by ldeviveiros** [comment]
It's not a permissions problem -  I changed permissions for the folder "N:\Data\Commissioning" so that the user project8 has full control, we still get the same error.

**Comment by nsoblath** [comment]
I'm not able to duplicate this problem in tests.  While processing an example egg file I do not see the error message from hashing.  And here's the AMQP message that was broadcast about the file, including the hash value:

```
2015-08-24T17:53:06[Level 35] dripline.core.service(305) -> Received message #1
application: None
routing_key: rsa_acquisition_table
{
    "timestamp": "2015-08-24T2424:53:06Z", 
    "sender_info": {
        "username": "irene\\project8", 
        "exe": "C:\\Users\\project8\\My Documents\\Go\\bin\\hornet.exe", 
        "package": "hornet", 
        "hostname": "IRENE", 
        "version": "v2.4.3", 
        "commit": "v2.4.3-0-g48f3cb8"
    }, 
    "retcode": 0, 
    "payload": {
        "file_hash": "d41d8cd98f00b204e9800998ecf8427e", 
        "file_name": "rid000000001_test.egg", 
        "fname_other": "test", 
        "values": [
            "do_insert"
        ], 
        "run_id": "000000001"
    }, 
    "msgop": 9
}
```

**Comment by nsoblath** [comment]
This was a configuration problem, and has been resolved.
